[package]
authors.workspace = true
categories.workspace = true
description = "Configuration discovery and TOML resolution for mdwright"
edition.workspace = true
license.workspace = true
keywords.workspace = true
readme.workspace = true
name = "mdwright-config"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
mdwright-document = { workspace = true }
mdwright-format = { workspace = true }
mdwright-lint = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = "3"

[lints]
workspace = true
