[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
mdwright = { path = ".." }
regex = "1"
toml = { version = "0.8", default-features = false, features = ["parse"] }
