//! Curated LaTeX-command → Unicode translation table.
//!
//! Used by [`super::latex_command::LatexCommand`] and exposed
//! publicly so user rules can share the same convention. Returns
//! `None` for commands that need an argument (`\bar{}`,
//! `\overline{}`, etc.) or context the table does not have.

#[must_use]
pub fn latex_unicode(name: &str) -> Option<&'static str> {
    Some(match name {
        // operators / symbols
        "cdot" => "⋅",
        "circ" => "∘",
        "times" => "×",
        "to" => "→",
        "mapsto" => "↦",
        "otimes" => "⊗",
        "oplus" => "⊕",
        "hookrightarrow" => "↪",
        "leftrightarrow" => "↔",
        "Longrightarrow" => "⟹",
        "Leftrightarrow" => "⟺",
        "dashrightarrow" => "⇢",
        "curvearrowright" => "↷",
        "bullet" => "•",
        "partial" => "∂",
        "nabla" => "∇",
        "prime" => "′",
        "wedge" => "∧",
        "vee" => "∨",
        "cup" => "∪",
        "cap" => "∩",
        "bigcup" => "⋃",
        "bigcap" => "⋂",
        "emptyset" => "∅",
        "infty" => "∞",
        "cong" => "≅",
        "sim" => "∼",
        "leq" => "≤",
        "geq" => "≥",
        "neq" => "≠",
        "subset" => "⊂",
        "subseteq" => "⊆",
        "in" => "∈",
        "ni" => "∋",
        "notin" => "∉",
        "forall" => "∀",
        "exists" => "∃",
        "langle" => "⟨",
        "rangle" => "⟩",
        "setminus" => "∖",

        // lowercase Greek
        "alpha" => "α",
        "beta" => "β",
        "gamma" => "γ",
        "delta" => "δ",
        "epsilon" => "ε",
        "zeta" => "ζ",
        "eta" => "η",
        "theta" => "θ",
        "iota" => "ι",
        "kappa" => "κ",
        "lambda" => "λ",
        "mu" => "μ",
        "nu" => "ν",
        "xi" => "ξ",
        "pi" => "π",
        "rho" => "ρ",
        "sigma" => "σ",
        "tau" => "τ",
        "phi" => "φ",
        "chi" => "χ",
        "psi" => "ψ",
        "omega" => "ω",

        // uppercase Greek
        "Gamma" => "Γ",
        "Delta" => "Δ",
        "Theta" => "Θ",
        "Lambda" => "Λ",
        "Pi" => "Π",
        "Sigma" => "Σ",
        "Phi" => "Φ",
        "Psi" => "Ψ",
        "Omega" => "Ω",

        _ => return None,
    })
}
