[package]
authors.workspace = true
categories.workspace = true
description = "Command-line delivery for mdwright"
edition.workspace = true
license.workspace = true
keywords.workspace = true
readme.workspace = true
name = "mdwright-cli"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ignore = { workspace = true }
mdwright-config = { workspace = true }
mdwright-document = { workspace = true }
mdwright-format = { workspace = true }
mdwright-lint = { workspace = true }
mdwright-lsp = { workspace = true }
owo-colors = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strsim = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
