[alias]
xtask = "run --quiet --package xtask --"

[patch.crates-io]
mdwright = { path = "crates/mdwright" }
mdwright-config = { path = "crates/mdwright-config" }
mdwright-document = { path = "crates/mdwright-document" }
mdwright-format = { path = "crates/mdwright-format" }
mdwright-lint = { path = "crates/mdwright-lint" }
mdwright-lsp = { path = "crates/mdwright-lsp" }
mdwright-math = { path = "crates/mdwright-math" }
